;;; init-pdf.el --- PDF reading and annotation -*- lexical-binding: t; -*-

;;; Commentary:
;; init-ui.el already disables line numbers in pdf-view-mode-hook,
;; which implies pdf-tools was expected to be installed -- it wasn't
;; wired up anywhere. This module adds it, plus org-noter so PDF
;; annotations can live alongside org-roam notes.
;;
;; One-time native compile step (pdf-tools compiles a small C helper,
;; epdfinfo): on first install it runs automatically via
;; `pdf-tools-install'. Make sure build deps are present:
;;   macOS:   brew install pkg-config poppler automake
;;   Ubuntu:  sudo apt install libpoppler-glib-dev libpoppler-private-dev \
;;              zlib1g-dev libpng-dev automake autoconf pkg-config

;;; Code:

;; ==================================================
;; pdf-tools (replaces the built-in DocView for PDFs)
;; ==================================================

(use-package pdf-tools
  :ensure t
  :defer t
  :mode ("\\.pdf\\'" . pdf-view-mode)
  :init
  ;; Defer the (potentially slow, first-run) native module build/load
  ;; until a PDF is actually opened, rather than at startup.
  (pdf-loader-install)

  :config
  (setq-default pdf-view-display-size 'fit-page)

  ;; Keep PDFs in sync if regenerated by latexmk/pandoc while open
  (add-hook 'pdf-view-mode-hook #'auto-revert-mode)

  ;; Note: pdf-tools scrolls page-by-page by default, not continuously.
  ;; For continuous scroll add the separate `pdf-continuous-scroll-mode'
  ;; package (requires Emacs built with SVG support).

  :bind (:map pdf-view-mode-map
              ("j" . pdf-view-next-line-or-next-page)
              ("k" . pdf-view-previous-line-or-previous-page)
              ("h" . pdf-view-previous-page-command)
              ("l" . pdf-view-next-page-command)))

;; ==================================================
;; org-noter: annotate PDFs, notes land in org-roam
;; ==================================================

(use-package org-noter
  :ensure t
  :after (:any org pdf-view)
  :config
  (setq org-noter-notes-window-location 'horizontal-split
        org-noter-auto-save-last-location t
        org-noter-always-create-frame nil
        org-noter-notes-search-path (list org-roam-directory)))

;; ==================================================
;; Provide
;; ==================================================

(provide 'init-pdf)

;;; init-pdf.el ends here
